# Generated by Django 4.2.9 on 2026-03-16 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Matière')),
                ('level', models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire (CP-CM2)'), ('college', 'Collège (6e-3e)'), ('lycee', 'Lycée (2nde-Terminale)'), ('superieur', 'Enseignement Supérieur'), ('formation', 'Formation Professionnelle')], max_length=50, verbose_name='Niveau scolaire')),
                ('theme', models.CharField(max_length=300, verbose_name='Thème du cours')),
                ('duration', models.CharField(max_length=100, verbose_name='Durée')),
                ('target_skills', models.TextField(verbose_name='Compétences visées')),
                ('pedagogical_objectives', models.TextField(verbose_name='Objectifs pédagogiques')),
                ('generated_title', models.CharField(blank=True, max_length=400)),
                ('generated_objectives', models.TextField(blank=True)),
                ('generated_prerequisites', models.TextField(blank=True)),
                ('generated_introduction', models.TextField(blank=True)),
                ('generated_plan', models.JSONField(blank=True, default=list)),
                ('generated_activities', models.JSONField(blank=True, default=list)),
                ('generated_materials', models.JSONField(blank=True, default=list)),
                ('generated_conclusion', models.TextField(blank=True)),
                ('generated_mcq', models.JSONField(blank=True, default=list)),
                ('generated_open_questions', models.JSONField(blank=True, default=list)),
                ('generated_practical_exercise', models.TextField(blank=True)),
                ('generated_answer_key', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan pédagogique',
                'verbose_name_plural': 'Plans pédagogiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
